---
- name: Configure Cisco Lines
  hosts: switches
  gather_facts: no
  connection: network_cli
  vars_files:
    - /home/serverlocal/cisco_timeExec/cisco_creds.yml

  tasks:

    # VLAN 261
    - name: Configure uRPF for Layer3 Interface VLAN 261
      cisco.ios.ios_config:
        lines:
          - ip verify unicast source reachable-via rx
        parents: interface vlan 261

    # VLAN 262
    - name: Configure uRPF for Layer3 Interface VLAN 262
      cisco.ios.ios_config:
        lines:
          - ip verify unicast source reachable-via rx
        parents: interface vlan 262

    # VLAN 280
    - name: Configure uRPF for Layer3 Interface VLAN 280
      cisco.ios.ios_config:
        lines:
          - ip verify unicast source reachable-via rx
        parents: interface vlan 280

    ###### Uncomment if you want to include VLAN 281 (caution with applications)
    # - name: Configure uRPF for Layer3 Interface VLAN 281
    #   cisco.ios.ios_config:
    #     lines:
    #       - ip verify unicast source reachable-via rx
    #     parents: interface vlan 281

    # VLAN 282
    - name: Configure uRPF for Layer3 Interface VLAN 282
      cisco.ios.ios_config:
        lines:
          - ip verify unicast source reachable-via rx
        parents: interface vlan 282

    # VLAN 284
    - name: Configure uRPF for Layer3 Interface VLAN 284
      cisco.ios.ios_config:
        lines:
          - ip verify unicast source reachable-via rx
        parents: interface vlan 284

    # VLAN 287
    - name: Configure uRPF for Layer3 Interface VLAN 287
      cisco.ios.ios_config:
        lines:
          - ip verify unicast source reachable-via rx
        parents: interface vlan 287

    # VLAN 288
    - name: Configure uRPF for Layer3 Interface VLAN 288
      cisco.ios.ios_config:
        lines:
          - ip verify unicast source reachable-via rx
        parents: interface vlan 288

    # VLAN 298
    - name: Configure uRPF for Layer3 Interface VLAN 298
      cisco.ios.ios_config:
        lines:
          - ip verify unicast source reachable-via rx
        parents: interface vlan 298
